//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOTBO.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WOTBO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///;Audio Latency
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\BackgroundModel\BackgroundAudioPolicy]
        ///&quot;AllowHeadlessExecution&quot;=dword:00000001
        ///&quot;AllowMultipleBackgroundTasks&quot;=dword:00000001
        ///&quot;InactivityTimeoutMs&quot;=dword:FFFFFFFF.
        /// </summary>
        internal static string Audio_Lantency {
            get {
                return ResourceManager.GetString("Audio_Lantency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\BackgroundModel\BackgroundAudioPolicy]
        ///&quot;AllowHeadlessExecution&quot;=dword:00000000
        ///&quot;InactivityTimeoutMs&quot;=dword:0000ea60
        ///.
        /// </summary>
        internal static string Audio_Lantency_delete {
            get {
                return ResourceManager.GetString("Audio_Lantency_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Base_Profile {
            get {
                object obj = ResourceManager.GetObject("Base_Profile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set &quot;TI=%windir%\oixro\su.exe /wrs cmd.exe /c &quot;
        ///taskkill /f /im explorer.exe &gt;nul 2&gt;&amp;1
        ///
        ///del &quot;%APPDATA%\Microsoft\Windows\Start Menu\Programs\System Tools\File Explorer.lnk&quot; &gt;nul 2&gt;&amp;1
        ///del &quot;%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\File Explorer.lnk&quot; &gt;nul 2&gt;&amp;1
        ///
        ///%TI% ren &quot;%windir%\SystemResources\imageres.dll.mun&quot; imageres.dll.mun_bak
        ///
        ///timeout /t 1 /nobreak &gt;nul
        ///
        ///%TI% copy &quot;%windir%\oixro\BlueIcon Minimal\imageres.dll.mun&quot; &quot;%windir%\SystemResources&quot;
        ///
        ///reg add &quot;HKCR\CompressedFolder\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string blueicons {
            get {
                return ResourceManager.GetString("blueicons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set &quot;TI=%windir%\oixro\su.exe /wrs cmd.exe /c &quot;
        ///taskkill /f /im explorer.exe &gt;nul 2&gt;&amp;1
        ///
        ///%TI% ren &quot;%windir%\System32\imageres.dll&quot; &quot;imageres.dll_bak&quot;
        ///timeout /t 1 /nobreak &gt;nul
        ///%TI% copy &quot;%windir%\oixro\imageres.dll&quot; &quot;%windir%\System32&quot;
        ///
        ///pushd &quot;%userprofile%\AppData\Local\Microsoft\Windows\Explorer&quot;
        ///del /f /a:s IconCache* &gt;nul 2&gt;&amp;1
        ///del /f /a:s thumbcache* &gt;nul 2&gt;&amp;1
        ///del /f IconCache* &gt;nul 2&gt;&amp;1
        ///del /f thumbcache* &gt;nul 2&gt;&amp;1
        ///popd
        ///pushd &quot;%userprofile%\AppData\Local&quot;
        ///del /f /a:s IconCache* &gt;nul 2&gt;&amp;1
        ///del /f /a:s th [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string blueiconsw10 {
            get {
                return ResourceManager.GetString("blueiconsw10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set &quot;TI=%windir%\oixro\su.exe /wrs cmd.exe /c &quot;
        ///taskkill /f /im explorer.exe &gt;nul 2&gt;&amp;1
        ///
        ///%TI% del /q &quot;%windir%\SystemResources\imageres.dll.mun&quot;
        ///
        ///timeout /t 2 /nobreak &gt;nul
        ///
        ///%TI% ren &quot;%windir%\SystemResources\imageres.dll.mun_bak&quot; imageres.dll.mun
        ///
        ///del /q /f /a:h &quot;%windir%\windows.ico&quot; &gt;nul
        ///del /q /f /a:h &quot;%windir%\desktop.ini&quot; &gt;nul
        ///del /q /f /a:h &quot;%ProgramFiles%\x64.ico&quot; &gt;nul
        ///del /q /f /a:h &quot;%ProgramFiles%\desktop.ini&quot; &gt;nul
        ///del /q /f /a:h &quot;%ProgramFiles(x86)%\x86.ico&quot; &gt;nul
        ///del /q /f /a:h &quot;%ProgramFiles(x86) [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string defblueicons {
            get {
                return ResourceManager.GetString("defblueicons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на set &quot;TI=%windir%\oixro\su.exe /wrs cmd.exe /c &quot;
        ///taskkill /f /im explorer.exe &gt;nul 2&gt;&amp;1
        ///
        ///%TI% del /q &quot;%windir%\System32\imageres.dll&quot;
        ///timeout /t 1 /nobreak &gt;nul
        ///%TI% ren &quot;%windir%\System32\imageres.dll_bak&quot; imageres.dll
        ///
        ///pushd &quot;%userprofile%\AppData\Local\Microsoft\Windows\Explorer&quot;
        ///del /f /a:s IconCache* &gt;nul 2&gt;&amp;1
        ///del /f /a:s thumbcache* &gt;nul 2&gt;&amp;1
        ///del /f IconCache* &gt;nul 2&gt;&amp;1
        ///del /f thumbcache* &gt;nul 2&gt;&amp;1
        ///popd
        ///timeout /t 1 /nobreak &gt;nul
        ///pushd &quot;%userprofile%\AppData\Local&quot;
        ///del /f /a:s IconCache* &gt;nul 2&gt;&amp;1
        ///del  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string deficonsw10 {
            get {
                return ResourceManager.GetString("deficonsw10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на taskkill /f /IM explorer.exe
        ///start explorer.exe
        ///exit.
        /// </summary>
        internal static string explor {
            get {
                return ResourceManager.GetString("explor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] gear {
            get {
                object obj = ResourceManager.GetObject("gear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///; Windows_10+8.x_MouseFix_ItemsSize=100%_Scale=1-to-1_@6-of-11
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Mouse]
        ///
        ///&quot;MouseSensitivity&quot;=&quot;10&quot;
        ///&quot;MouseSpeed&quot;=&quot;0&quot;
        ///&quot;SmoothMouseXCurve&quot;=hex:\
        ///	00,00,00,00,00,00,00,00,\
        ///	C0,CC,0C,00,00,00,00,00,\
        ///	80,99,19,00,00,00,00,00,\
        ///	40,66,26,00,00,00,00,00,\
        ///	00,33,33,00,00,00,00,00
        ///&quot;SmoothMouseYCurve&quot;=hex:\
        ///	00,00,00,00,00,00,00,00,\
        ///	00,00,38,00,00,00,00,00,\
        ///	00,00,70,00,00,00,00,00,\
        ///	00,00,A8,00,00,00,00,00,\
        ///	00,00,E0,00,00,00,00,00
        ///
        ///[HKEY_USER [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string mousefix {
            get {
                return ResourceManager.GetString("mousefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters]
        ///&quot;EnablePrefetcher&quot;=dword:0
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SysMain]
        ///&quot;Start&quot;=dword:4
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SysMain\Parameters]
        ///&quot;ServiceDllUnloadOnStop&quot;=dword:0.
        /// </summary>
        internal static string prefetcher_hdd {
            get {
                return ResourceManager.GetString("prefetcher_hdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters]
        ///&quot;EnablePrefetcher&quot;=dword:3
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SysMain]
        ///&quot;Start&quot;=dword:2
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SysMain\Parameters]
        ///&quot;ServiceDllUnloadOnStop&quot;=dword:1.
        /// </summary>
        internal static string prefetcher_ssd {
            get {
                return ResourceManager.GetString("prefetcher_ssd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] regpack {
            get {
                object obj = ResourceManager.GetObject("regpack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
        ///&quot;DisableAntiSpyware&quot;=-
        ///&quot;DisableAntiVirus&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features]
        ///&quot;TamperProtection&quot;=dword:5
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\SmartScreen]
        ///&quot;ConfigureAppInstallControl&quot;=-
        ///&quot;ConfigureAppInstallControlEnabled&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SecurityHealthService]
        ///&quot;Start&quot;=dword:00000003
        ///
        ///[HKEY_LOCAL_MACHINE\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string restoreWINDEF10 {
            get {
                return ResourceManager.GetString("restoreWINDEF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
        ///&quot;DisableAntiSpyware&quot;=-
        ///&quot;DisableAntiVirus&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features]
        ///&quot;TamperProtection&quot;=dword:5
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\SmartScreen]
        ///&quot;ConfigureAppInstallControl&quot;=-
        ///&quot;ConfigureAppInstallControlEnabled&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SecurityHealthService]
        ///&quot;Start&quot;=dword:00000003
        ///
        ///[HKEY_LOCAL_MACHINE\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string restoreWINDEF11 {
            get {
                return ResourceManager.GetString("restoreWINDEF11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] scheme {
            get {
                object obj = ResourceManager.GetObject("scheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] su {
            get {
                object obj = ResourceManager.GetObject("su", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ui {
            get {
                object obj = ResourceManager.GetObject("ui", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Control Panel\Mouse]
        ///&quot;SmoothMouseXCurve&quot;=hex:\
        ///	00,00,00,00,00,00,00,00,\
        ///	15,6e,00,00,00,00,00,00,\
        ///	00,40,01,00,00,00,00,00,\
        ///	29,dc,03,00,00,00,00,00,\
        ///	00,00,28,00,00,00,00,00
        ///&quot;SmoothMouseYCurve&quot;=hex:\
        ///	00,00,00,00,00,00,00,00,\
        ///	fd,11,01,00,00,00,00,00,\
        ///	00,24,04,00,00,00,00,00,\
        ///	00,fc,12,00,00,00,00,00,\
        ///	00,c0,bb,01,00,00,00,00
        ///.
        /// </summary>
        internal static string unmousefix {
            get {
                return ResourceManager.GetString("unmousefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 	for /f &quot;tokens=*&quot; %%i in (&apos;reg query &quot;HKLM\SYSTEM\CurrentControlSet\Enum&quot; /s /f &quot;StorPort&quot; ^| findstr &quot;StorPort&quot;&apos;) do reg delete &quot;%%i&quot; /v &quot;EnableIdlePowerManagement&quot; /f
        ///	for /f &quot;tokens=*&quot; %%i in (&apos;wmic PATH Win32_PnPEntity GET DeviceID ^| findstr &quot;USB\VID_&quot;&apos;) do (
        ///	reg delete &quot;HKLM\System\CurrentControlSet\Enum\%%i\Device Parameters&quot; /v &quot;EnhancedPowerManagementEnabled&quot; /f
        ///	reg delete &quot;HKLM\System\CurrentControlSet\Enum\%%i\Device Parameters&quot; /v &quot;AllowIdleIrpInD3&quot; /f
        ///	reg delete &quot;HKLM\System\CurrentControlS [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string unusbpowersaving {
            get {
                return ResourceManager.GetString("unusbpowersaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Registry Editor Version 5.00
        ///
        ///; Создано с помощью Total Uninstall
        ///
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU]
        ///&quot;AUOptions&quot;=dword:00000002
        ///&quot;NoAutoUpdate&quot;=dword:00000001
        ///&quot;ScheduledInstallDay&quot;=dword:00000000
        ///&quot;ScheduledInstallTime&quot;=dword:00000003
        ///.
        /// </summary>
        internal static string updates {
            get {
                return ResourceManager.GetString("updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 	
        ///	for /f &quot;tokens=*&quot; %%i in (&apos;reg query &quot;HKLM\SYSTEM\CurrentControlSet\Enum&quot; /s /f &quot;StorPort&quot; ^| findstr &quot;StorPort&quot;&apos;) do reg add &quot;%%i&quot; /v &quot;EnableIdlePowerManagement&quot; /t REG_DWORD /d &quot;0&quot; /f
        ///	for /f &quot;tokens=*&quot; %%i in (&apos;wmic PATH Win32_PnPEntity GET DeviceID ^| findstr &quot;USB\VID_&quot;&apos;) do (
        ///	reg add &quot;HKLM\System\CurrentControlSet\Enum\%%i\Device Parameters&quot; /v &quot;EnhancedPowerManagementEnabled&quot; /t REG_DWORD /d &quot;0&quot; /f
        ///	reg add &quot;HKLM\System\CurrentControlSet\Enum\%%i\Device Parameters&quot; /v &quot;AllowIdleIrpInD3&quot; /t REG_DWO [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string usbpowersaving {
            get {
                return ResourceManager.GetString("usbpowersaving", resourceCulture);
            }
        }
    }
}
